package utility;

public class Constant {

	public static final Integer IC_NUMBER = 1;
	public static final Integer NAME = 2;
	public static final Integer SURNAME = 3;
	public static final Integer BIRTH_DATE = 4;
	public static final Integer STATE = 5;
	public static final Integer CITY = 6;
	public static final Integer HEIGHT = 7;
	
	public static final int MaxYearBirthDate = 2050;
	public static final int MinYearBirthDate = 1900;	
	public static final int NumberAutogeneratedCIty = 2451;
	public static final int NumberAutogeneratedICs = 1000;
	public static final int NumberAutogeneratedNames = 9118;
	public static final int NumberAutogeneratedSurnames = 802;
	public static String zero="0.00000000000000000001";


	
	
}
